name: Package File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Check for setup.py
      run: |
        if [ ! -f setup.py ]; then
          echo "Error: setup.py not found in the repository root."
          echo "Please ensure that setup.py exists in the root directory of your project."
          exit 1
        fi

    - name: Package file
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
